# Generated by Django 3.1.7 on 2021-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название Категория', max_length=100, verbose_name='Название Категории')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка')),
                ('title', models.CharField(help_text='введите название', max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('categories', models.ManyToManyField(to='my_projekt.Category', verbose_name='категория')),
            ],
        ),
    ]
